version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cookies-manager/laravel-app:latest
    container_name: laravel-app
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_KEY: base64:...
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: cookies_manager
      DB_USERNAME: root
      DB_PASSWORD: password123
    volumes:
      - .:/var/www
    networks:
      - laravel

  pgsql:
    image: postgres:15
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: cookies_manager
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgsql_data:

networks:
  laravel:
    driver: bridge
