version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cookies-manager/laravel-app:latest
    container_name: laravel-app
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_KEY: base64:...
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: cookies_manager
      DB_USERNAME: root
      DB_PASSWORD: password123
    volumes:
      - .:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cookies_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
