services:
  app:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./docker/prod/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_started

  pgsql:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel -d laravel"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: